# Generated by Django 2.2.24 on 2021-10-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('espesor', models.IntegerField()),
                ('tipo', models.BooleanField()),
                ('precio_neto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('n_pedido', models.IntegerField()),
                ('fecha', models.DateField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=50)),
                ('forma_pago', models.CharField(max_length=30)),
                ('tipo_facturacion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total_detalle', models.IntegerField()),
                ('piezas_paquete', models.IntegerField()),
                ('num_paquete', models.CharField(max_length=45)),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Producto')),
            ],
        ),
    ]
