# Generated by Django 2.2.24 on 2021-08-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('espesor', models.IntegerField()),
                ('tipo', models.BooleanField()),
                ('precio_neto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('tipo_compra', models.CharField(max_length=50)),
                ('forma_pago', models.CharField(max_length=30)),
                ('tipo_facturacion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Cliente')),
                ('producto', models.ManyToManyField(to='venta.Producto')),
            ],
        ),
    ]
