# Generated by Django 2.2.24 on 2021-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(max_length=11),
        ),
    ]
