# Generated by Django 2.2.24 on 2021-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20210826_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=60),
        ),
    ]
