# Generated by Django 2.2.24 on 2021-08-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210826_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden_compra',
            old_name='tipo_compra',
            new_name='tipo_pago',
        ),
    ]
