# Generated by Django 2.2.24 on 2021-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20210827_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='iva',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='num_pedido',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Orden_Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Producto')),
            ],
        ),
    ]
