# Generated by Django 2.2.24 on 2021-09-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20210903_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=64)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Region')),
            ],
        ),
    ]
