# Generated by Django 2.2.24 on 2021-09-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_comuna_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='region',
        ),
    ]
