# Generated by Django 2.2.24 on 2021-09-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_auto_20210903_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='total',
            new_name='total_detalle',
        ),
    ]
