# Generated by Django 2.2.24 on 2021-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_auto_20210907_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='total_detalle',
            field=models.IntegerField(null=True),
        ),
    ]
