# Generated by Django 2.2.24 on 2021-09-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_auto_20210908_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='neto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='venta.Orden_Compra'),
        ),
    ]
