# Generated by Django 2.2.24 on 2021-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_auto_20210909_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('n_pedido', models.IntegerField()),
                ('fecha', models.DateField()),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=234)),
                ('tipo', models.CharField(max_length=120)),
                ('descripcion_productos', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField()),
                ('paquete', models.CharField(max_length=50)),
                ('piezas_paquete', models.IntegerField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=50)),
                ('forma_pago', models.CharField(max_length=30)),
                ('tipo_facturacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='orden_compra',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='orden_compra',
            name='neto',
        ),
        migrations.RemoveField(
            model_name='orden_compra',
            name='total',
        ),
    ]
