# Generated by Django 2.2.24 on 2021-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_auto_20210923_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descripcion_productos',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='neto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='paquete',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='piezas_paquete',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_facturacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
