# Generated by Django 2.2.24 on 2021-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_auto_20210923_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden_compra', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='total_detalle',
            field=models.IntegerField(null=True),
        ),
    ]
