# Generated by Django 2.2.24 on 2021-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0020_auto_20210929_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='paquetes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
