# Generated by Django 2.2.24 on 2021-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0021_auto_20210929_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='paquetes',
            field=models.FloatField(),
        ),
    ]
